# Generated by Django 4.2.4 on 2023-08-20 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='is_active',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', through='post.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
