# Generated by Django 4.2.4 on 2023-08-30 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='participants',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
