# Generated by Django 4.2.4 on 2023-09-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='joinUser',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
