# Generated by Django 4.2.4 on 2023-08-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="profileImgae",
            new_name="profileImage",
        ),
    ]
